# K Mean Clustering 

### Import the libraries

In [36]:
import numpy as np
import cv2 as cv
from matplotlib import pyplot as plt

### Sapmle Input Data

In [ ]:
from PIL import Image
from IPython.display import display

# Specify the filenames of the images
image_filenames = ['1.jpg', '2.jpg', '3.jpg']

# Open and display each image
for filename in image_filenames:
    # Open the image using PIL
    image = Image.open(filename)

    # Define the desired width for the resized image
    desired_width = 250

    # Calculate the new height while maintaining the aspect ratio
    aspect_ratio = float(image.size[1]) / float(image.size[0])
    desired_height = int(aspect_ratio * desired_width)

    # Resize the image
    resized_image = image.resize((desired_width, desired_height))

    # Display the resized image
    display(resized_image)


### Read the images

In [ ]:
input_img_1 = cv.imread('1.jpg')
input_img_2 = cv.imread('2.jpg')
input_img_3 = cv.imread('3.jpg')

#Information of images
print("shapes of images:")
print('Image 1: ', input_img_1.shape)
print('Image 2: ', input_img_2.shape)
print('Image 3: ', input_img_3.shape)



### Under Standing the data

In [ ]:
#printing the first 2 rows of the image
print("Image 1 : ROW1:")
print(input_img_1[0:1].shape)
print(input_img_1[0:1])

### Preprocessing the data

In [ ]:
#_________________This code will need your attention to run properly____________

#convert the image 1 to 2D array
input_img_1_2d = 
print("Image 1 : 2D array:")
print(input_img_1_2d.shape)

#convert the image 2 to 2D array
input_img_2_2d = 
print("Image 2 : 2D array:")
print(input_img_2_2d.shape)

#convert the image 3 to 2D array
input_img_3_2d = 
print("Image 3 : 2D array:")
print(input_img_3_2d.shape)

#convert the image 1 to 2D array
input_img_1_2d = input_img_1.reshape((input_img_1.shape[0] * input_img_1.shape[1], input_img_1.shape[2]))


##### Expected Output

Image 1 : 2D array:
(558000, 3) <br>
Image 2 : 2D array:
(426400, 3) <br>
Image 3 : 2D array:
(275100, 3) <br>

### Implimentation of K-Mean Clustering

In [32]:
def kmeans_clustering(data, k, max_iterations=100):
    # Randomly initialize centroids
    centroids = data[np.random.choice(data.shape[0], k, replace=False)]

    for _ in range(max_iterations):
        # Assign each data point to the nearest centroid
        distances = np.sqrt(((data - centroids[:, np.newaxis])**2).sum(axis=2))
        labels = np.argmin(distances, axis=0)

        # Update centroids by taking the mean of the assigned data points
        new_centroids = np.array([data[labels == i].mean(axis=0) for i in range(k)])

        # Check convergence
        if np.all(centroids == new_centroids):
            break

        centroids = new_centroids

    return labels, centroids



In [62]:
k = 2  # Number of clusters
labels, centroids = kmeans_clustering(input_img_1_2d, k)
print('Labels shape: ', labels.shape)
print('Centroids shape: ', centroids.shape)
centroids

Labels shape:  (558000,)
Centroids shape:  (2, 3)


array([[146.69424657, 165.29740674, 178.57222286],
       [ 59.52581169,  67.58876255,  95.28271327]])

In [63]:
print(np.unique(labels))
print(centroids)

[0 1]
[[146.69424657 165.29740674 178.57222286]
 [ 59.52581169  67.58876255  95.28271327]]


In [69]:
original_shape = input_img_1.shape

clustered_image = labels.reshape((744, 750, 3))


ValueError: cannot reshape array of size 558000 into shape (744,750,3)

#### Regenrate clustered image

#### Plotting the clustered image